dataset: "cifar10"
model: "cnn_cifar"  # "linear", "mlp", "mlp_tanh", "cnn", "cnn_tanh" or "cnn_cifar"
do_accounting: True
label_privacy: False
binary: False
pca_dims: 0
batch_size: 200
momentum_mass: 0.5
num_epochs: 150
optimizer: "sgd"  # "sgd" or "adam"
step_size: 0.03
weight_decay: 0
sigma: 0.5
norm_clip: 1
delta: 1e-10
